In [109]:
#importing necessary libraries
import pandas as pd
import numpy as np

In [110]:
data_ = pd.read_csv('./dummy.csv')
data_.head(3)

gender smoking_history    bmi  bmi.1  HbA1c_level  blood_glucose_level  \
0  Female           never  25.19  25.19          6.6                  140   
1  Female         No Info  27.32  27.32          6.6                   80   
2    Male           never  27.32  27.32          5.7                  158   

   diabetes  
0         0  
1         0  
2         0

In [111]:
# Explore basic statistics
print(data_.describe())

                 bmi          bmi.1    HbA1c_level  blood_glucose_level  \
count  100000.000000  100000.000000  100000.000000        100000.000000   
mean       27.320767      27.320767       5.527507           138.058060   
std         6.636783       6.636783       1.070672            40.708136   
min        10.010000      10.010000       3.500000            80.000000   
25%        23.630000      23.630000       4.800000           100.000000   
50%        27.320000      27.320000       5.800000           140.000000   
75%        29.580000      29.580000       6.200000           159.000000   
max        95.690000      95.690000       9.000000           300.000000   

            diabetes  
count  100000.000000  
mean        0.085000  
std         0.278883  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  


In [112]:
data_.shape

(100000, 7)

Error Handling

In [113]:
data_.isnull().sum()

gender                 0
smoking_history        0
bmi                    0
bmi.1                  0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [114]:
data_.dropna(inplace=True)

In [115]:
data_.shape

(100000, 7)

Encode

In [116]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder


# Assuming data_ is your DataFrame
x = data_.iloc[:, :-1].values
y = data_.iloc[:, -1].values

print("normal x value\n",x)
# label encoder 
#female = 0 
#male = 1
label_encoder = LabelEncoder()
x[:, 0] = label_encoder.fit_transform(x[:, 0])

print("label encode gender value\n",x)


# Use ColumnTransformer for OneHotEncoding
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder="passthrough")
x = np.array(ct.fit_transform(x))
print("OneHot Encoding\n",x)
print("y values\n",y)

normal x value
 [['Female' 'never' 25.19 25.19 6.6 140]
 ['Female' 'No Info' 27.32 27.32 6.6 80]
 ['Male' 'never' 27.32 27.32 5.7 158]
 ...
 ['Male' 'former' 27.83 27.83 5.7 155]
 ['Female' 'never' 35.42 35.42 4.0 100]
 ['Female' 'current' 22.43 22.43 6.6 90]]
label encode gender value
 [[0 'never' 25.19 25.19 6.6 140]
 [0 'No Info' 27.32 27.32 6.6 80]
 [1 'never' 27.32 27.32 5.7 158]
 ...
 [1 'former' 27.83 27.83 5.7 155]
 [0 'never' 35.42 35.42 4.0 100]
 [0 'current' 22.43 22.43 6.6 90]]
OneHot Encoding
 [[0.0 0.0 0.0 ... 25.19 6.6 140]
 [1.0 0.0 0.0 ... 27.32 6.6 80]
 [0.0 0.0 0.0 ... 27.32 5.7 158]
 ...
 [0.0 0.0 0.0 ... 27.83 5.7 155]
 [0.0 0.0 0.0 ... 35.42 4.0 100]
 [0.0 1.0 0.0 ... 22.43 6.6 90]]
y values
 [0 0 0 ... 0 0 0]


Split dataset

In [117]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=1)

In [118]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.0 0.0 0.0 ... 29.45 6.0 90]
 [1.0 0.0 0.0 ... 25.88 3.5 90]
 [0.0 0.0 1.0 ... 34.19 6.5 130]
 ...
 [0.0 0.0 0.0 ... 28.36 5.8 90]
 [0.0 0.0 0.0 ... 57.51 6.2 126]
 [0.0 0.0 0.0 ... 27.32 6.0 90]]
[[1.0 0.0 0.0 ... 26.62 5.0 155]
 [0.0 0.0 0.0 ... 27.32 4.5 130]
 [1.0 0.0 0.0 ... 27.32 6.2 130]
 ...
 [0.0 0.0 0.0 ... 25.55 5.8 100]
 [1.0 0.0 0.0 ... 41.04 6.1 158]
 [0.0 0.0 0.0 ... 45.03 4.5 158]]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


feature scaling

In [119]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train[:,4:]= scaler.fit_transform(x_train[:,4:])
x_test[:,4:]= scaler.fit_transform(x_test[:,4:])


print(x_test)
print(x_train)

[[1.0 0.0 0.0 ... -0.10317360764541834 -0.4940076505670938
  0.40407221124724485]
 [0.0 0.0 0.0 ... 0.0025901545363380607 -0.9617765825111954
  -0.20830068030419413]
 [1.0 0.0 0.0 ... 0.0025901545363380607 0.6286377860987503
  -0.20830068030419413]
 ...
 [0.0 0.0 0.0 ... -0.2648410726946748 0.25442264054346864
  -0.9431481501659209]
 [1.0 0.0 0.0 ... 2.0755598932987653 0.5350839997099295
  0.47755695823341754]
 [0.0 0.0 0.0 ... 2.678413337734778 -0.9617765825111954
  0.47755695823341754]]
[[0.0 0.0 0.0 ... 0.3192937198691135 0.44121232678317046
  -1.177359364274938]
 [1.0 0.0 0.0 ... -0.21799021979413086 -1.8921368373906409
  -1.177359364274938]
 [0.0 0.0 1.0 ... 1.0326623120270342 0.9078821596179327
  -0.1935007452707305]
 ...
 [0.0 0.0 0.0 ... 0.15524904361338904 0.2545443936492654
  -1.177359364274938]
 [0.0 0.0 0.0 ... 4.542315385681616 0.6278802599170755
  -0.2918866071711513]
 [0.0 0.0 0.0 ... -0.0012706474929901161 0.44121232678317046
  -1.177359364274938]]
